import type Database from "better-sqlite3";
import { randomUUID } from "node:crypto";
import { mkdirSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { getDb } from "../db.js";
import type { HomeserverConfig } from "./config.js";
import { AdmissionController, AdmissionRejected } from "./admission.js";
import { reconcileCredits, recordUsage as recordCreditUsage } from "./keystore.js";
import { recordUsage, dayKey, type QuotaReservation } from "./quota.js";
import { generateImages, ImageSidecarError } from "./image-sidecar.js";
import { recordImagesGenerated, inflightInc, inflightDec } from "./metrics.js";
import { recordRequestLog } from "./request-log.js";
import { recordOwnerRequest } from "./owner-log.js";
import type { ParsedImageRequest } from "./image-request.js";

/**
 * Async image-generation job store + single-slot worker.
 *
 * CONTENT-BLINDNESS — the load-bearing invariant. The durable `image_jobs` table is METADATA-ONLY:
 * its columns are accounting + status only (see COLUMNS / imageJobColumns()). The PROMPT, the SIZE,
 * the generated bytes, and the quota reservation handle live ONLY in an in-memory spec map that is
 * NEVER persisted. Consequence: a crash loses in-flight specs, and restart recovery marks any
 * orphaned queued/running row failed + refunds its credits (the prompt never survives a restart).
 *
 * The generated images ARE written to disk transiently (so an async client can fetch them) under
 * cfg.imageResultDir, swept after cfg.imageResultTtlMs. That result store is NOT a log — it is the
 * delivery buffer, TTL-deleted, referenced only by the job's result_path.
 *
 * Worker state is keyed by AdmissionController so multiple gateways in one process (tests) each get
 * their own queue without a global singleton clobbering.
 */

// ─── Schema (content-blind) ─────────────────────────────────────────────────────────

/** The ordered column list — single source of truth for the schema AND the privacy assertion. */
const COLUMNS = [
  "id",
  "ts",
  "alias",
  "key_hash",
  "tier",
  "model",
  "status",
  "n",
  "credits_reserved",
  "credits_charged",
  "quota_alias",
  "quota_day",
  "quota_reserved_daily",
  "result_path",
  "expires_at",
  "error_class",
] as const;

/** Expose the column names so a test can assert no prompt/bytes/size content column exists. */
export function imageJobColumns(): string[] {
  return [...COLUMNS];
}

let _init = false;

function ensureSchema(db: Database.Database): void {
  if (_init) return;
  db.exec(`
    CREATE TABLE IF NOT EXISTS image_jobs (
      id               TEXT PRIMARY KEY,
      ts               INTEGER NOT NULL,
      alias            TEXT,
      key_hash         TEXT,
      tier             TEXT,
      model            TEXT NOT NULL,
      status           TEXT NOT NULL,
      n                INTEGER NOT NULL,
      credits_reserved INTEGER NOT NULL DEFAULT 0,
      credits_charged  INTEGER,
      quota_alias      TEXT,
      quota_day        TEXT,
      quota_reserved_daily INTEGER,
      result_path      TEXT,
      expires_at       INTEGER,
      error_class      TEXT
    );
    CREATE INDEX IF NOT EXISTS idx_image_jobs_status ON image_jobs(status);
    CREATE INDEX IF NOT EXISTS idx_image_jobs_alias  ON image_jobs(alias);
  `);
  // Additive migration for image_jobs tables created before the quota-refund columns (PR #60).
  for (const [col, type] of [["quota_day", "TEXT"], ["quota_reserved_daily", "INTEGER"]] as const) {
    try {
      db.exec(`ALTER TABLE image_jobs ADD COLUMN ${col} ${type}`);
    } catch (e) {
      if (!String((e as Error).message).includes("duplicate column")) throw e;
    }
  }
  _init = true;
}

function db(): Database.Database {
  const d = getDb();
  ensureSchema(d);
  return d;
}

/** Eagerly create the image_jobs schema (idempotent). For tests + migrations. */
export function ensureImageJobsSchema(): void {
  ensureSchema(getDb());
}

interface ImageJobDbRow {
  id: string;
  ts: number;
  alias: string | null;
  key_hash: string | null;
  tier: string | null;
  model: string;
  status: string;
  n: number;
  credits_reserved: number;
  credits_charged: number | null;
  quota_alias: string | null;
  quota_day: string | null;
  quota_reserved_daily: number | null;
  result_path: string | null;
  expires_at: number | null;
  error_class: string | null;
}

// ─── Public types ────────────────────────────────────────────────────────────────────

/** Everything the worker needs that is NOT persisted (prompt/size + reconcile handles). */
export interface ImageJobSubmission {
  parsed: ParsedImageRequest;
  alias: string;
  keyHash: string | null;
  lane: "owner" | "guest";
  /** Worst-case credits already reserved by the gateway handler (0 when not capped). */
  creditsReserved: number;
  /** Whether reserveCredits() actually took credits (keyHash !== null && creditLimit > 0). */
  capped: boolean;
  creditsPerImage: number;
  /** The quota reservation handle to reconcile when the job settles. */
  quotaReservation: QuotaReservation;
  /** Concrete sidecar model id (the advertised image-* alias resolves to this). */
  backendModel: string;
  /** Capture the prompt to the owner-log (owner tier + real key + ownerRequestLog on). */
  ownerCapture: boolean;
}

/** The client-facing job view (202 submit + GET poll). */
export interface ImageJobView {
  id: string;
  status: string;
  model: string;
  n: number;
  created: number; // epoch seconds (OpenAI convention)
  expiresAt: number | null;
  errorClass: string | null;
  data?: Array<{ b64_json: string }>;
}

interface JobSpec {
  submission: ImageJobSubmission;
  abort: AbortController;
  cancelled: boolean;
  timedOut: boolean;
}

interface WorkerCtx {
  cfg: HomeserverConfig;
  controller: AdmissionController;
  queue: string[];
  specs: Map<string, JobSpec>;
  pumping: boolean;
  stopped: boolean;
  sweepTimer: ReturnType<typeof setInterval> | null;
}

const workers = new Map<AdmissionController, WorkerCtx>();

// ─── Result file helpers ───────────────────────────────────────────────────────────

function resultPathFor(cfg: HomeserverConfig, id: string): string {
  return join(cfg.imageResultDir, `${id}.json`);
}

function writeResult(cfg: HomeserverConfig, id: string, b64: string[]): string {
  mkdirSync(cfg.imageResultDir, { recursive: true });
  const path = resultPathFor(cfg, id);
  writeFileSync(path, JSON.stringify({ b64 }), "utf-8");
  return path;
}

function readResult(path: string): string[] | null {
  try {
    const parsed = JSON.parse(readFileSync(path, "utf-8")) as { b64?: unknown };
    return Array.isArray(parsed.b64) ? (parsed.b64 as string[]) : null;
  } catch {
    return null;
  }
}

function deleteResult(path: string | null): void {
  if (!path) return;
  try {
    rmSync(path, { force: true });
  } catch {
    /* best-effort */
  }
}

// ─── Row helpers ─────────────────────────────────────────────────────────────────────

function readRow(id: string): ImageJobDbRow | undefined {
  return db().prepare(`SELECT * FROM image_jobs WHERE id = ?`).get(id) as ImageJobDbRow | undefined;
}

function viewFromRow(row: ImageJobDbRow, includeData: boolean): ImageJobView {
  const view: ImageJobView = {
    id: row.id,
    status: row.status,
    model: row.model,
    n: row.n,
    created: Math.floor(row.ts / 1000),
    expiresAt: row.expires_at,
    errorClass: row.error_class,
  };
  if (includeData && row.status === "succeeded" && row.result_path) {
    const b64 = readResult(row.result_path);
    if (b64) view.data = b64.map((s) => ({ b64_json: s }));
  }
  return view;
}

/** Whether `principal` is the creator of `row` (strict creator scoping; no admin override). */
function ownsRow(row: ImageJobDbRow, principal: { keyHash: string | null; alias: string }): boolean {
  if (principal.keyHash !== null) return row.key_hash === principal.keyHash;
  return row.key_hash === null && row.alias === principal.alias;
}

// ─── Submit ──────────────────────────────────────────────────────────────────────────

/**
 * Persist a queued job + stash its in-memory spec + enqueue it. The gateway handler has ALREADY
 * reserved credits + quota (so it could return 402/429 synchronously) — this only records and
 * schedules. Returns the 202 view.
 */
export function submitImageJob(controller: AdmissionController, sub: ImageJobSubmission): ImageJobView {
  const ctx = workers.get(controller);
  if (!ctx) throw new Error("image worker not started for this controller");

  const id = `imgjob_${randomUUID()}`;
  const ts = Date.now();
  const expiresAt = ts + ctx.cfg.imageResultTtlMs;
  db()
    .prepare(
      `INSERT INTO image_jobs
         (id, ts, alias, key_hash, tier, model, status, n, credits_reserved, credits_charged,
          quota_alias, quota_day, quota_reserved_daily, result_path, expires_at, error_class)
       VALUES
         (@id, @ts, @alias, @keyHash, @tier, @model, 'queued', @n, @creditsReserved, NULL,
          @quotaAlias, @quotaDay, @quotaReservedDaily, NULL, @expiresAt, NULL)`
    )
    .run({
      id,
      ts,
      alias: sub.alias,
      keyHash: sub.keyHash,
      tier: sub.lane,
      model: sub.parsed.model,
      n: sub.parsed.n,
      creditsReserved: sub.creditsReserved,
      quotaAlias: sub.quotaReservation.alias,
      quotaDay: sub.quotaReservation.day,
      quotaReservedDaily: sub.quotaReservation.reservedDaily,
      expiresAt,
    });

  // Build the 202 view BEFORE pumping — pump() runs synchronously up to its first await and would
  // otherwise flip the row to 'running' before we read it back.
  const view: ImageJobView = {
    id,
    status: "queued",
    model: sub.parsed.model,
    n: sub.parsed.n,
    created: Math.floor(ts / 1000),
    expiresAt,
    errorClass: null,
  };

  ctx.specs.set(id, { submission: sub, abort: new AbortController(), cancelled: false, timedOut: false });
  ctx.queue.push(id);
  void pump(ctx);

  return view;
}

// ─── Read / cancel ─────────────────────────────────────────────────────────────────

/** Read a job by id, scoped to its creator. Returns null when not found OR not owned (→ bare 404). */
export function getImageJob(
  id: string,
  principal: { keyHash: string | null; alias: string }
): ImageJobView | null {
  const row = readRow(id);
  if (!row || !ownsRow(row, principal)) return null;
  return viewFromRow(row, true);
}

/**
 * Cancel + refund a job, idempotently. Refund happens ONLY if this call wins the terminal transition
 * (guarded UPDATE from queued|running) — so a job that already settled is a no-op (no double refund).
 * Returns {found:false} when the job doesn't exist or isn't owned by the principal (→ 404).
 */
export function cancelImageJob(
  controller: AdmissionController,
  id: string,
  principal: { keyHash: string | null; alias: string }
): { found: boolean; status?: string } {
  const row = readRow(id);
  if (!row || !ownsRow(row, principal)) return { found: false };

  const ctx = workers.get(controller);
  const spec = ctx?.specs.get(id);

  const info = db()
    .prepare(`UPDATE image_jobs SET status = 'cancelled' WHERE id = ? AND status IN ('queued','running')`)
    .run(id);
  if (info.changes > 0) {
    // We won the transition → we own the refund.
    if (spec) {
      spec.cancelled = true;
      spec.abort.abort();
      ctx!.queue = ctx!.queue.filter((q) => q !== id);
      refundJob(spec.submission);
      ctx!.specs.delete(id);
    } else {
      // No in-memory spec (e.g. a row that outlived its process): refund from the persisted row —
      // lifetime credits + the daily quota reservation (the RPM/TPM ring is gone; daily is durable).
      refundOrphanRow(row);
    }
    deleteResult(row.result_path);
    return { found: true, status: "cancelled" };
  }
  // Already terminal — idempotent.
  return { found: true, status: readRow(id)?.status };
}

// ─── Metering reconcile ───────────────────────────────────────────────────────────────

function refundJob(sub: ImageJobSubmission): void {
  if (sub.keyHash !== null && sub.capped) {
    reconcileCredits(sub.keyHash, sub.creditsReserved, 0); // full refund
  }
  // Release the quota reservation (TPM event + daily) back to 0.
  recordUsage(sub.quotaReservation.alias, 0, Date.now(), sub.quotaReservation);
}

function settleCredits(sub: ImageJobSubmission, charged: number): void {
  if (sub.keyHash === null) return;
  if (sub.capped) reconcileCredits(sub.keyHash, sub.creditsReserved, charged);
  else recordCreditUsage(sub.keyHash, charged); // uncapped minted key accrues real usage
}

// ─── Worker ────────────────────────────────────────────────────────────────────────

/**
 * Start the single-slot diffusion worker for this controller. Idempotent per controller. Runs
 * restart-recovery first (orphaned queued/running → failed + refund), then arms the TTL sweep.
 */
export function startImageWorker(
  cfg: HomeserverConfig,
  controller: AdmissionController
): { stop: () => void } {
  ensureSchema(getDb());
  const existing = workers.get(controller);
  if (existing) return { stop: () => stopWorker(controller) };

  recoverOrphans(cfg);

  const ctx: WorkerCtx = {
    cfg,
    controller,
    queue: [],
    specs: new Map(),
    pumping: false,
    stopped: false,
    sweepTimer: null,
  };
  const sweep = setInterval(() => sweepExpired(cfg), Math.min(cfg.imageResultTtlMs, 60_000));
  if (typeof sweep.unref === "function") sweep.unref();
  ctx.sweepTimer = sweep;
  workers.set(controller, ctx);
  return { stop: () => stopWorker(controller) };
}

function stopWorker(controller: AdmissionController): void {
  const ctx = workers.get(controller);
  if (!ctx) return;
  ctx.stopped = true;
  if (ctx.sweepTimer) clearInterval(ctx.sweepTimer);
  // Abort any in-flight spec so a slow dispatch doesn't outlive the gateway.
  for (const spec of ctx.specs.values()) spec.abort.abort();
  workers.delete(controller);
}

/**
 * Refund an orphaned/cancelled job from its PERSISTED row (no live in-memory spec): lifetime credits
 * + the daily quota reservation. The RPM/TPM ring is gone after a restart, but the daily counter is
 * durable, so recordUsage(...,0,...) → adjustDaily releases it. Pre-migration rows (NULL quota_day /
 * quota_reserved_daily) fall back to `n` image-units reserved on the submit day (dayKey(ts)).
 */
function refundOrphanRow(row: ImageJobDbRow): void {
  if (row.key_hash !== null && row.credits_reserved > 0) {
    reconcileCredits(row.key_hash, row.credits_reserved, 0);
  }
  if (row.quota_alias !== null) {
    recordUsage(row.quota_alias, 0, Date.now(), {
      alias: row.quota_alias,
      eventId: "", // the in-memory ring is empty at this point; only the daily counter is refunded
      reservedDaily: row.quota_reserved_daily ?? row.n,
      day: row.quota_day ?? dayKey(row.ts),
    });
  }
}

/** Restart recovery: a queued/running row from a prior process has no in-memory spec → fail+refund. */
function recoverOrphans(cfg: HomeserverConfig): void {
  const orphans = db()
    .prepare(`SELECT * FROM image_jobs WHERE status IN ('queued','running')`)
    .all() as ImageJobDbRow[];
  for (const row of orphans) {
    const info = db()
      .prepare(
        `UPDATE image_jobs SET status = 'failed', error_class = 'interrupted'
         WHERE id = ? AND status IN ('queued','running')`
      )
      .run(row.id);
    if (info.changes > 0) refundOrphanRow(row);
    deleteResult(row.result_path);
  }
}

function setStatusRunning(id: string): boolean {
  return db().prepare(`UPDATE image_jobs SET status = 'running' WHERE id = ? AND status = 'queued'`).run(id).changes > 0;
}

/**
 * #108 follow-up: submission is maintenance-gated for guests, but the worker's OWN admission
 * request (acquireSlot, below) always uses lane:"owner" — a deliberate internal-priority choice
 * unrelated to who submitted the job — so without this check a guest job already queued before
 * maintenance mode engages would still execute during the window. A job with no live spec (about
 * to be cleaned up by processJob's own "!spec" branch) is left eligible so it drains promptly
 * rather than getting stuck as a phantom skip.
 */
function isEligibleNow(ctx: WorkerCtx, id: string): boolean {
  const spec = ctx.specs.get(id);
  if (!spec) return true;
  return spec.submission.lane !== "guest" || !ctx.controller.isMaintenanceMode();
}

async function pump(ctx: WorkerCtx): Promise<void> {
  if (ctx.pumping) return;
  ctx.pumping = true;
  try {
    while (!ctx.stopped && ctx.queue.length > 0) {
      // Scan for the first RUNNABLE job rather than blindly shifting the front — a paused guest
      // job must never head-of-line-block a later owner job (owner traffic is never blocked by
      // maintenance mode, even when it arrives after a guest job that's currently paused).
      const idx = ctx.queue.findIndex((qid) => isEligibleNow(ctx, qid));
      if (idx === -1) {
        // Everything left in the queue is a guest job paused for maintenance. Wait and rescan
        // instead of spinning; bounded by the loop's own re-check of stopped/queue.length each
        // pass, same 250ms cadence as acquireSlot's busy-retry below.
        await new Promise<void>((resolve) => {
          const t = setTimeout(resolve, 250);
          if (typeof t.unref === "function") t.unref(); // don't pin the process alive during a long maintenance window
        });
        continue;
      }
      const id = ctx.queue.splice(idx, 1)[0]!;
      await processJob(ctx, id);
    }
  } finally {
    ctx.pumping = false;
  }
}

function delay(ms: number, signal: AbortSignal): Promise<void> {
  return new Promise((resolve) => {
    const t = setTimeout(resolve, ms);
    if (typeof t.unref === "function") t.unref();
    signal.addEventListener("abort", () => {
      clearTimeout(t);
      resolve();
    });
  });
}

/** Acquire the shared admission slot as an owner-lane request, retrying while LLM slots are saturated. */
async function acquireSlot(ctx: WorkerCtx, signal: AbortSignal): Promise<() => void> {
  for (;;) {
    if (signal.aborted) throw new ImageSidecarError("cancelled before dispatch", "upstream_unavailable");
    try {
      return await ctx.controller.acquire({
        lane: "owner",
        requestedModel: null,
        keyMaxParallel: Math.max(1, ctx.cfg.imageGpuSlots),
        keyInflight: 0,
        keyId: "image-worker",
      });
    } catch (err) {
      if (err instanceof AdmissionRejected) {
        await delay(250, signal); // slots busy; back off and retry (bounded by the job timeout)
        continue;
      }
      throw err;
    }
  }
}

async function processJob(ctx: WorkerCtx, id: string): Promise<void> {
  const spec = ctx.specs.get(id);
  if (!spec) return; // cancelled/removed before dispatch
  if (!setStatusRunning(id)) {
    ctx.specs.delete(id); // cancelled while queued
    return;
  }

  const timer = setTimeout(() => {
    spec.timedOut = true;
    spec.abort.abort();
  }, ctx.cfg.imageJobTimeoutMs);
  if (typeof timer.unref === "function") timer.unref();

  const start = Date.now();
  let release: (() => void) | null = null;
  let held = false;
  try {
    release = await acquireSlot(ctx, spec.abort.signal);
    inflightInc("owner");
    held = true;
    const b64 = await generateImages(
      ctx.cfg.imageUrl,
      { prompt: spec.submission.parsed.prompt, model: spec.submission.backendModel, n: spec.submission.parsed.n, size: spec.submission.parsed.size },
      ctx.cfg.imageJobTimeoutMs,
      spec.abort.signal
    );
    finalizeSuccess(ctx, id, spec, b64, Date.now() - start);
  } catch (err) {
    if (spec.cancelled) return; // cancelJob already settled the row + refund
    const errorClass = spec.timedOut
      ? "upstream_timeout"
      : err instanceof ImageSidecarError
        ? err.kind
        : "internal_error";
    finalizeFailure(ctx, id, spec, errorClass, Date.now() - start);
  } finally {
    clearTimeout(timer);
    if (release) release();
    if (held) inflightDec("owner");
    ctx.specs.delete(id);
  }
}

function finalizeSuccess(ctx: WorkerCtx, id: string, spec: JobSpec, b64: string[], durationMs: number): void {
  const sub = spec.submission;
  const delivered = b64.length;
  const charged = delivered * sub.creditsPerImage;
  const resultPath = writeResult(ctx.cfg, id, b64);
  const won = db()
    .prepare(
      `UPDATE image_jobs SET status = 'succeeded', credits_charged = @charged, result_path = @resultPath
       WHERE id = @id AND status = 'running'`
    )
    .run({ id, charged, resultPath }).changes > 0;
  if (!won) {
    deleteResult(resultPath); // cancel won the race — discard the bytes, refund already done
    return;
  }
  settleCredits(sub, charged);
  recordUsage(sub.quotaReservation.alias, delivered, Date.now(), sub.quotaReservation);
  recordImagesGenerated(sub.parsed.model, delivered);
  logCompletion(sub, 200, "ok", delivered, durationMs, null);
  if (sub.ownerCapture) {
    recordOwnerRequest({
      alias: sub.alias,
      model: sub.parsed.model,
      route: "image",
      messagesJson: JSON.stringify({ prompt: sub.parsed.prompt, size: sub.parsed.size, n: sub.parsed.n }),
      completion: `${delivered} image(s) generated`,
      promptTokens: null,
      completionTokens: null,
      latencyMs: durationMs,
      tokPerSec: null,
      outcome: "ok",
    });
  }
}

function finalizeFailure(ctx: WorkerCtx, id: string, spec: JobSpec, errorClass: string, durationMs: number): void {
  const sub = spec.submission;
  const won = db()
    .prepare(`UPDATE image_jobs SET status = 'failed', error_class = @errorClass WHERE id = @id AND status = 'running'`)
    .run({ id, errorClass }).changes > 0;
  if (!won) return; // cancel won — refund already done
  refundJob(sub);
  const status = errorClass === "upstream_timeout" ? 504 : 502;
  logCompletion(sub, status, errorClass, 0, durationMs, errorClass);
}

/** Best-effort content-blind completion row (the worker has no lctx — it logs its own row). */
function logCompletion(
  sub: ImageJobSubmission,
  status: number,
  outcome: string,
  delivered: number,
  durationMs: number,
  errorClass: string | null
): void {
  recordRequestLog({
    requestId: randomUUID(),
    alias: sub.alias,
    tier: sub.lane,
    keyHash: sub.keyHash,
    model: sub.parsed.model,
    route: "image",
    status,
    outcome,
    errorClass,
    promptTokens: null,
    completionTokens: null,
    totalTokens: delivered,
    queueWaitMs: null,
    ttftMs: null,
    totalMs: durationMs,
    admission: "admitted",
  });
}

/** Sweep finished jobs past their TTL: delete the bytes + mark expired so GET stops returning data. */
function sweepExpired(cfg: HomeserverConfig): void {
  const now = Date.now();
  const stale = db()
    .prepare(`SELECT * FROM image_jobs WHERE status = 'succeeded' AND expires_at IS NOT NULL AND expires_at < ?`)
    .all(now) as ImageJobDbRow[];
  for (const row of stale) {
    deleteResult(row.result_path);
    db().prepare(`UPDATE image_jobs SET status = 'expired', result_path = NULL WHERE id = ?`).run(row.id);
  }
}
