import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const root = new URL("..", import.meta.url).pathname;
const script = join(root, "scripts", "service-isolation.sh");

function render(service: string): string {
  const out = mkdtempSync(join(tmpdir(), "gille-isolation-render-"));
  execFileSync("bash", [script, "render", "--service", service, "--output-dir", out], {
    cwd: root,
    encoding: "utf8",
  });
  return readFileSync(join(out, `${service}.conf`), "utf8");
}

function runGatewayApplyFailureHarness(): string {
  const work = mkdtempSync(join(tmpdir(), "gille-isolation-harness-"));
  const log = join(work, "order.log");
  const harness = join(work, "harness.sh");
  writeFileSync(harness, `#!/usr/bin/env bash
LOG="$2"; BACKUP_ROOT="$3"; source "$1"
record() { printf '%s\\n' "$1" >> "$LOG"; }
root_only() { :; }; need() { :; }; show_value() { printf 'magnus\\n'; }
preflight() { :; }; create_service_user() { :; }; prepare_gateway_user_manager() { :; }; provision_gateway_codeloop_runtime() { :; }; install() { :; }; stat() { printf '1\\n'; }
backup_unit() { mkdir -p "$3"; printf 'enabled\\n' > "$3/legacy-timer.enabled"; printf 'active\\n' > "$3/legacy-timer.active"; }
disable_legacy_autonomy_timer() { record disable; }
migrate_gateway_state() { record migrate; false; }
cleanup_gateway_partial_secret() { record cleanup; }
restore_legacy_autonomy_timer() { record restore; }
systemctl() { [ "$1" = is-active ] && return 0; return 0; }
apply gateway "$BACKUP_ROOT"
`, { mode: 0o755 });
  try {
    execFileSync("bash", [harness, script, log, work], { cwd: root, encoding: "utf8" });
  } catch {
    // The intentional migration failure propagates after the EXIT handler restores safety.
  }
  return readFileSync(log, "utf8");
}

function runUserManagerHarness(readyOnAttempt: number | null): { status: number; output: string } {
  const work = mkdtempSync(join(tmpdir(), "gille-user-manager-harness-"));
  const harness = join(work, "harness.sh");
  writeFileSync(harness, `#!/usr/bin/env bash
source "$1"
attempt=0
id() { printf '4242\\n'; }
loginctl() { if [ "$1" = show-user ]; then printf 'yes\\n'; else return 0; fi; }
systemctl() { [ "$1" = start ] && printf 'started:%s\\n' "$2"; }
gateway_user_bus_ready() { attempt=$((attempt + 1)); [ "$attempt" -ge "${readyOnAttempt ?? 999}" ]; }
runuser() { printf 'probe\\n'; }
sleep() { :; }
prepare_gateway_user_manager
`, { mode: 0o755 });
  try {
    return { status: 0, output: execFileSync("bash", [harness, script], { cwd: root, encoding: "utf8", stderr: "pipe" }) };
  } catch (error: any) {
    return { status: error.status ?? 1, output: `${error.stdout ?? ""}${error.stderr ?? ""}` };
  }
}

describe("service-isolation migration contract (#151)", () => {
  it("waits for a delayed lingered user manager bus after explicitly starting user@UID", () => {
    const result = runUserManagerHarness(3);
    expect(result.status).toBe(0);
    expect(result.output).toContain("started:user@4242.service");
  });

  it("fails closed with actionable user-manager context when the bus never becomes ready", () => {
    const result = runUserManagerHarness(null);
    expect(result.status).not.toBe(0);
    expect(result.output).toContain("did not become ready after 10s");
    expect(result.output).toContain("journalctl -u user@4242.service");
  });

  it("allows only reviewed Pi package provenance when cloning the code-loop runtime", () => {
    const mario = "/home/magnus/.local/lib/node_modules/@mariozechner/pi-coding-agent/dist/cli.js";
    const earendil = "/home/magnus/.local/lib/node_modules/@earendil-works/pi-coding-agent/dist/cli.js";
    expect(execFileSync("bash", ["-c", "source \"$1\"; gateway_codeloop_package_from_resolved_path \"$2\"", "--", script, mario], { encoding: "utf8" }).trim()).toBe("@mariozechner/pi-coding-agent");
    expect(execFileSync("bash", ["-c", "source \"$1\"; gateway_codeloop_package_from_resolved_path \"$2\"", "--", script, earendil], { encoding: "utf8" }).trim()).toBe("@earendil-works/pi-coding-agent");
    expect(() => execFileSync("bash", ["-c", "source \"$1\"; gateway_codeloop_package_from_resolved_path \"$2\"", "--", script, "/tmp/unknown/cli.js"], { encoding: "utf8" })).toThrow();
  });

  it("is executable from the committed tree for the documented direct invocation", () => {
    expect(statSync(script).mode & 0o111).not.toBe(0);
    expect(execFileSync(script, ["--help"], { cwd: root, encoding: "utf8" })).toContain("Usage: scripts/service-isolation.sh");
  });

  it.each(["gateway", "cloudflared", "llama-swap"])("renders a fail-closed hardened %s drop-in", (service) => {
    const unit = render(service);
    expect(unit).toContain("# Generated by scripts/service-isolation.sh; do not hand-edit.");
    expect(unit).toContain("NoNewPrivileges=true");
    expect(unit).toContain("ProtectSystem=strict");
    expect(unit).toContain("ProtectHome=tmpfs");
    expect(unit).toContain("PrivateTmp=true");
    expect(unit).toContain("RestrictSUIDSGID=true");
    expect(unit).toContain("UMask=0077");
    expect(unit).toContain("CapabilityBoundingSet=");
    expect(unit).not.toContain("User=magnus");
  });

  it("keeps the gateway's durable state and secret file outside the owner home", () => {
    const unit = render("gateway");
    expect(unit).toContain("User=gille-gateway");
    expect(unit).toContain("EnvironmentFile=/etc/gille-inference/gateway/gateway.env");
    expect(unit).toContain("BindPaths=/var/lib/gille-inference/gateway/data:/home/magnus/home-server-eval/data");
    expect(unit).toContain("BindReadOnlyPaths=/home/magnus/home-server-eval");
    expect(unit).toContain("InaccessiblePaths=-/home/magnus/home-server-eval/.claude");
    expect(unit).toContain("InaccessiblePaths=-/home/magnus/home-server-eval/.ssh");
    expect(unit).not.toContain("BindReadOnlyPaths=/home/magnus\n");
    expect(unit).toContain("Environment=HOMESERVER_CODE_LOOP_WORKROOT=/var/lib/gille-inference/gateway/data/code-loop-work");
    expect(unit).not.toContain("/var/lib/gille-inference/gateway/code-loop-work");
    expect(unit).toContain("Environment=HOMESERVER_CODE_LOOP_PI_BIN=/var/lib/gille-inference/gille-gateway/.local/bin/pi");
    expect(unit).toContain("Environment=HOMESERVER_CODE_LOOP_PI_AGENT_DIR=/var/lib/gille-inference/gille-gateway/.pi-code-loop");
  });

  it("allows cloudflared only the network and files it requires", () => {
    const unit = render("cloudflared");
    expect(unit).toContain("User=gille-cloudflared");
    expect(unit).toContain("ExecStart=/usr/bin/cloudflared --config /etc/gille-inference/cloudflared/config.yml --no-autoupdate tunnel run m5-inference");
    expect(unit).toContain("ReadOnlyPaths=/etc/gille-inference/cloudflared");
    expect(unit).toContain("MemoryDenyWriteExecute=true");
  });

  it("keeps llama-swap loopback-only and explicitly grants the render device group", () => {
    const unit = render("llama-swap");
    expect(unit).toContain("User=gille-llama-swap");
    expect(unit).toContain("SupplementaryGroups=render video");
    expect(unit).toContain("BindReadOnlyPaths=/home/magnus/models");
    expect(unit).toContain("BindReadOnlyPaths=/home/magnus/llama.cpp");
    expect(unit).toContain("DeviceAllow=/dev/dri/renderD128 rw");
    expect(unit).toContain("DeviceAllow=/dev/dri/card0 rw");
    expect(unit).toContain("IPAddressDeny=any");
    expect(unit).toContain("IPAddressAllow=127.0.0.0/8");
    expect(unit).toContain("IPAddressAllow=::1/128");
  });

  it("rejects unknown services and does not silently apply all services", () => {
    expect(() => execFileSync("bash", [script, "render", "--service", "all"], { cwd: root, encoding: "utf8" }))
      .toThrow(/unknown service/i);
  });

  it("keeps code-loop auth and owner-home paths out of the migration payload", () => {
    const source = readFileSync(script, "utf8");
    expect(source).toContain("loginctl enable-linger");
    expect(source).toContain("DBUS_SESSION_BUS_ADDRESS");
    expect(source).toContain("dedicated Pi runtime contains auth.json");
    expect(source).toContain("[ ! -e \"$home/.pi-code-loop/auth.json\" ]");
    expect(source).not.toContain("BindReadOnlyPaths=/home/magnus\n");
    expect(source).toContain("InaccessiblePaths=-$GATEWAY_TREE/.claude");
    expect(source).toContain("list-units 'code-loop-*.scope' --state=active --no-legend --plain)\" || die \"could not query Magnus code-loop scopes");
    expect(source).toContain("[ -z \"$active_scopes\" ] || die \"active Magnus code-loop scope exists");
    expect(source).toContain("show gille-autonomy-tick.service -p ActiveState --value)\" || die \"could not query Magnus autonomy tick state");
    expect(source).toContain('case "$autonomy_state" in inactive|failed)');
    expect(source).not.toContain("cp -a \"$source_agent\"");
  });

  it("has a real one-service rollback path and keeps tunnel credentials root-owned", () => {
    const source = readFileSync(script, "utf8");
    expect(source).toContain('chown -R "root:$TUNNEL_USER" "$ETC/cloudflared"');
    expect(source).toContain('find "$ETC/cloudflared" -type d -exec chmod 0750 {} +');
    expect(source).toContain('find "$ETC/cloudflared" -type f -exec chmod 0640 {} +');
    expect(source).toContain('find "$ETC/cloudflared" \\( ! -user root -o ! -group "$TUNNEL_USER" \\) -print -quit');
    expect(source).toContain('rm -f "$dropin"');
    expect(source).toContain('mv "$ROOT/gateway/data" "$GATEWAY_DATA"');
    expect(source).toContain('mv "$ETC/cloudflared" "$TUNNEL_SOURCE"');
    expect(source).toContain('rollback-receipt');
  });

  it("does not duplicate or overwrite state during an apply/rollback lifecycle", () => {
    const source = readFileSync(script, "utf8");
    expect(source).toContain('[ ! -e "/etc/systemd/system/$unit.d/50-service-isolation.conf" ]');
    expect(source).toContain('[ ! -d "$ROOT/gateway/data" ] || rmdir "$ROOT/gateway/data"');
    expect(source).toContain('mv "$LLAMA_TREE/config.yaml" "$ETC/llama-swap/config.yaml"');
    expect(source).toContain('[ ! -e "$LLAMA_TREE/config.yaml" ] || die "legacy llama-swap config remains in owner home"');
    expect(source).toContain('rm -f "$ETC/gateway/gateway.env"');
    expect(source).toContain('mv "$ETC/llama-swap/config.yaml" "$LLAMA_TREE/config.yaml"');
  });

  it("moves the autonomy cadence with gateway state instead of leaving the owner timer behind", () => {
    const source = readFileSync(script, "utf8");
    expect(source).toContain("disable_legacy_autonomy_timer");
    expect(source).toContain("install_gateway_autonomy_timer");
    expect(source).toContain("Environment=GILLE_AUTONOMY_ENV_FILE=$ETC/gateway/gateway.env");
    expect(source).toContain("systemctl is-active --quiet gille-autonomy-tick.timer");
  });

  it("uses the configured tailnet listener rather than assuming gateway loopback", () => {
    const source = readFileSync(script, "utf8");
    expect(source).toContain("gateway_health_url()");
    expect(source).toContain('"$(gateway_health_url)"');
    expect(source).not.toContain("http://127.0.0.1:8080/healthz");
  });

  it("makes repeat apply and rollback verified no-ops", () => {
    const source = readFileSync(script, "utf8");
    expect(source).toContain("NO-OP: $service is already isolated and verified");
    expect(source).toContain("NO-OP: $service is already rolled back and verified");
    expect(source).toContain('systemctl stop "$unit" || die "could not stop $unit; refusing rollback mutation"');
    expect(source).toContain("isolated autonomy timer stayed active");
    expect(source).toContain('if ! verify "$service" 0; then');
    expect(source).toContain('rollback_feasible "$service"\n  install_dropin "$service"');
  });

  it("verifies effective systemd capability, filesystem, and loopback/device constraints", () => {
    const source = readFileSync(script, "utf8");
    expect(source).toContain('require_show_empty "$unit" CapabilityBoundingSet');
    expect(source).toContain('require_show_exact_set "$unit" BindPaths "$ROOT/gateway/data:$GATEWAY_DATA"');
    expect(source).toContain('require_show_exact_set "$unit" InaccessiblePaths "-$GATEWAY_TREE/.claude"');
    expect(source).toContain('[ "$(show_value "$unit" DevicePolicy)" = closed ]');
    expect(source).toContain('require_show_exact_device_allow "$unit" "/dev/null:rw"');
    expect(source).toContain('require_show_exact_set "$unit" IPAddressDeny 0.0.0.0/0 ::/0');
    expect(source).toContain('require_show_exact_set "$unit" IPAddressAllow 127.0.0.0/8 ::1/128');
  });

  it("normalizes canonical bind modifiers and rejects extra effective allowlist entries", () => {
    const normalized = execFileSync("bash", ["-c", "source \"$1\"; printf '%s\\n' '/a:/a:rbind /b:rw /c' | normalize_show_set", "--", script], { encoding: "utf8" });
    expect(normalized.trim().split("\n")).toEqual(["/a", "/b", "/c"]);
    const source = readFileSync(script, "utf8");
    expect(source).toContain('require_show_exact_set "$unit" BindPaths "$ROOT/gateway/data:$GATEWAY_DATA"');
    expect(source).toContain('require_show_exact_set "$unit" RestrictAddressFamilies AF_UNIX AF_INET AF_INET6');
    expect(source).toContain('require_show_empty "$unit" BindReadOnlyPaths');
    expect(source).toContain('require_show_empty "$unit" BindPaths');
    expect(source).toContain('effective $property differs from the reviewed allowlist');
    expect(source).toContain('effective DeviceAllow differs from the reviewed allowlist');
  });

  it("restores the legacy timer when gateway state migration fails after it was disabled", () => {
    expect(runGatewayApplyFailureHarness().trim().split("\n")).toEqual(["disable", "migrate", "cleanup", "restore"]);
  });

  it("distinguishes sudo's successful no-rule listing from an actual command grant", () => {
    const denied = "User gille-gateway is not allowed to run sudo on m5.";
    const granted = "User gille-gateway may run the following commands on m5:\n    (ALL) NOPASSWD: ALL";
    expect(execFileSync("bash", ["-c", "source \"$1\"; sudo_output_is_nonprivileged \"$2\"", "--", script, denied], { encoding: "utf8" })).toBe("");
    expect(() => execFileSync("bash", ["-c", "source \"$1\"; sudo_output_is_nonprivileged \"$2\"", "--", script, granted], { encoding: "utf8" }))
      .toThrow();
  });

  it("keeps the shared config parent traversable across sequential service migrations", () => {
    const source = readFileSync(script, "utf8");
    expect(source).toContain('install -d -m 0755 -o root -g root "$ETC"');
    expect(source).toContain('install -d -m 0750 -o root -g "$GATEWAY_USER" "$ETC/gateway"');
    expect(source).toContain('install -d -m 0750 -o root -g "$LLAMA_USER" "$ETC/llama-swap"');
  });
});
