// ORACLE — the ground-truth check. Do NOT edit this file (the harness must make the
// implementation satisfy it). Exits non-zero on any failed assertion.
import assert from "node:assert/strict";
import { sum } from "../src/sum.ts";

assert.equal(sum([1, 2, 3]), 6, "sum([1,2,3]) should be 6");
assert.equal(sum([]), 0, "sum([]) should be 0");
assert.equal(sum([-1, 1]), 0, "sum([-1,1]) should be 0");
assert.equal(sum([5]), 5, "sum([5]) should be 5");
console.log("oracle: PASS");
