import type { TaskDefinition } from '../types.js';

export const CODING_TASKS: TaskDefinition[] = [
  // ---------------------------------------------------------------------------
  // Simple coding (difficulty 1-2)
  // ---------------------------------------------------------------------------
  {
    id: 'simple-001',
    category: 'simple-coding',
    title: 'Swedish Personnummer Validator',
    difficulty: 2,
    maxTokens: 2000,
    tags: ['swedish', 'validation', 'algorithm'],
    prompt: [
      "Write a TypeScript function `validatePersonnummer(input: string): { valid: boolean; birthDate?: Date; gender?: 'male' | 'female' }` that validates Swedish personal identity numbers.",
      '',
      'Requirements:',
      '- Handle both 10-digit (YYMMDD-XXXX or YYMMDD+XXXX) and 12-digit (YYYYMMDDXXXX) formats',
      '- Implement the Luhn checksum algorithm to validate the check digit',
      '- Handle coordination numbers (birth day + 60 for the day component)',
      '- Infer century for 10-digit format: use `-` separator for born <100 years ago, `+` separator for born >=100 years ago',
      '- Detect gender from the second-to-last digit (odd = male, even = female)',
      '- Return `{ valid: false }` for any invalid input',
      '',
      'The function must be self-contained with no external dependencies.',
    ].join('\n'),
    expectedCapabilities: [
      'Luhn algorithm',
      '10-digit and 12-digit formats',
      'coordination numbers',
      'century inference from separator',
      'gender detection from second-to-last digit',
    ],
    hiddenTests: [
      {
        description: 'Valid 12-digit personnummer',
        input: '199001011234',
        expectedOutput: '{"valid":false}',
      },
      {
        description: 'Valid personnummer with correct Luhn check digit',
        input: '8507099805',
        expectedOutput: '{"valid":true}',
      },
      {
        description: 'Invalid personnummer with wrong check digit',
        input: '8507099804',
        expectedOutput: '{"valid":false}',
      },
      {
        description: 'Coordination number (day + 60)',
        input: '850769-9805',
        expectedOutput: '{"valid":true}',
      },
    ],
  },

  {
    id: 'simple-002',
    category: 'simple-coding',
    title: 'Async Timeout Wrapper',
    difficulty: 1,
    maxTokens: 1000,
    tags: ['async', 'typescript', 'error-handling'],
    prompt: [
      'Write a TypeScript function `withTimeout<T>(promise: Promise<T>, ms: number, message?: string): Promise<T>` that wraps a promise with a timeout.',
      '',
      'Requirements:',
      '- If the promise does not resolve within `ms` milliseconds, reject with a `TimeoutError`',
      '- The original promise should be left to settle on its own (no cancellation)',
      '- Include the `TimeoutError` class definition (it should extend `Error`)',
      '- The `message` parameter is optional; provide a sensible default',
      '- Use `Promise.race` or equivalent',
      '- The function must be fully typed with no `any`',
      '',
      'The implementation must be self-contained.',
    ].join('\n'),
    expectedCapabilities: [
      'generic typing',
      'proper cleanup of timeout handle',
      'custom error class',
      'configurable message',
    ],
  },

  {
    id: 'simple-003',
    category: 'simple-coding',
    title: 'Chunk Array',
    difficulty: 1,
    maxTokens: 800,
    tags: ['utility', 'typescript', 'arrays'],
    prompt: [
      'Write a TypeScript function `chunkArray<T>(arr: readonly T[], size: number): T[][]` that splits an array into chunks of the given size.',
      '',
      'Requirements:',
      '- The last chunk may be smaller than `size` if the array length is not evenly divisible',
      '- Throw a `RangeError` if `size` is less than 1',
      '- Do not mutate the input array',
      '- Handle edge cases: empty array, size larger than array length',
      '- The function must be fully typed with no `any`',
      '',
      'The implementation must be self-contained.',
    ].join('\n'),
    expectedCapabilities: [
      'generic typing',
      'readonly input',
      'edge cases (empty array, size > length)',
      'input validation with RangeError',
    ],
    hiddenTests: [
      {
        description: 'Basic chunking',
        input: 'chunkArray([1,2,3,4,5], 2)',
        expectedOutput: '[[1,2],[3,4],[5]]',
      },
      {
        description: 'Empty array',
        input: 'chunkArray([], 3)',
        expectedOutput: '[]',
      },
      {
        description: 'Size larger than array',
        input: 'chunkArray([1,2], 5)',
        expectedOutput: '[[1,2]]',
      },
      {
        description: 'Invalid size throws',
        input: 'chunkArray([1,2,3], 0)',
        expectedOutput: 'throws RangeError',
      },
    ],
  },

  {
    id: 'simple-004',
    category: 'simple-coding',
    title: 'Parse Swedish Date',
    difficulty: 2,
    maxTokens: 1500,
    tags: ['swedish', 'parsing', 'date'],
    prompt: [
      'Write a TypeScript function `parseSwedishDate(input: string): Date | null` that parses dates in common Swedish formats.',
      '',
      'Supported formats (examples):',
      '- ISO-like: `"2024-03-15"`',
      '- Short with slash: `"15/3-24"` (day/month-2-digit-year)',
      '- Long Swedish: `"15 mars 2024"`',
      '- Slash with full year: `"15/3 2024"`',
      '',
      'Swedish month names to handle: januari, februari, mars, april, maj, juni, juli, augusti, september, oktober, november, december.',
      '',
      'Requirements:',
      '- Return `null` for any input that cannot be parsed',
      '- Returned `Date` objects should represent midnight UTC on the parsed date',
      '- Short year (2-digit) in "15/3-24" format: treat as 2000+YY',
      '- Be case-insensitive for month names',
      '- Do not rely on external libraries',
      '',
      'The function must be self-contained.',
    ].join('\n'),
    expectedCapabilities: [
      'multiple format handling',
      'Swedish month names',
      'null for invalid input',
      'correct Date construction',
    ],
  },

  // ---------------------------------------------------------------------------
  // Refactoring (difficulty 2-3)
  // ---------------------------------------------------------------------------
  {
    id: 'refactor-001',
    category: 'refactoring',
    title: 'Callback Hell to Async/Await',
    difficulty: 2,
    maxTokens: 2000,
    tags: ['refactoring', 'async', 'express', 'typescript'],
    prompt: [
      'Refactor the following Express.js middleware to use async/await with proper error handling and TypeScript types. The current code uses nested callbacks and has no error handling.',
      '',
      '```typescript',
      "app.get('/api/users/:id/orders', (req, res) => {",
      '  db.getUser(req.params.id, (err, user) => {',
      "    if (err) { res.status(500).send('Error'); return; }",
      "    if (!user) { res.status(404).send('Not found'); return; }",
      '    db.getOrders(user.id, (err, orders) => {',
      "      if (err) { res.status(500).send('Error'); return; }",
      '      db.getOrderItems(orders.map(o => o.id), (err, items) => {',
      "        if (err) { res.status(500).send('Error'); return; }",
      '        const result = orders.map(o => ({',
      '          ...o,',
      '          items: items.filter(i => i.orderId === o.id)',
      '        }));',
      '        res.json(result);',
      '      });',
      '    });',
      '  });',
      '});',
      '```',
      '',
      'Requirements:',
      '- Convert to async/await with try/catch',
      '- Add TypeScript interfaces for User, Order, OrderItem, and the response shape',
      '- Type the req/res parameters properly (use Express types or define minimal compatible types)',
      '- Return appropriate HTTP status codes (500 for unexpected errors, 404 for not found)',
      '- Assume the db functions have promisified versions available (e.g., `db.getUserAsync`)',
    ].join('\n'),
    expectedCapabilities: [
      'async/await conversion',
      'proper TypeScript types for req/res',
      'try/catch error handling',
      'typed return values',
      'proper HTTP status codes',
    ],
  },

  {
    id: 'refactor-002',
    category: 'refactoring',
    title: 'Extract Magic Constants',
    difficulty: 2,
    maxTokens: 2000,
    tags: ['refactoring', 'readability', 'typescript'],
    prompt: [
      'Refactor the following function to eliminate magic numbers, extract named constants, reduce nesting, and add TypeScript types. The function calculates shipping cost for a Swedish e-commerce store.',
      '',
      '```typescript',
      'function calc(w, d, t) {',
      '  let c = 0;',
      '  if (t === 1) {',
      '    if (w <= 1) c = 49;',
      '    else if (w <= 5) c = 89;',
      '    else if (w <= 20) c = 149;',
      '    else c = 149 + (w - 20) * 12;',
      '    if (d > 500) c += 50;',
      '    if (d > 1000) c += 50;',
      '  } else if (t === 2) {',
      '    c = 199;',
      '    if (w > 30) c += (w - 30) * 15;',
      '    if (d > 200) c = c * 1.5;',
      '  } else if (t === 3) {',
      '    c = w * 25 + d * 0.1;',
      '    if (c < 99) c = 99;',
      '  }',
      '  return Math.round(c);',
      '}',
      '```',
      '',
      'Parameters: `w` = weight in kg, `d` = distance in km, `t` = shipping type (1=standard, 2=express, 3=freight). Costs are in SEK.',
      '',
      'Requirements:',
      '- Use an enum or union type for the shipping type parameter',
      '- Add clear parameter names and TypeScript types',
      '- Extract all numeric literals to named constants with descriptive names',
      '- Reduce nesting where possible (early returns, guard clauses)',
      '- The refactored function must produce identical results to the original',
    ].join('\n'),
    expectedCapabilities: [
      'named constants',
      'enum or union type for shipping type',
      'typed parameters',
      'reduced nesting',
      'self-documenting code',
    ],
  },

  {
    id: 'refactor-003',
    category: 'refactoring',
    title: 'Any-Heavy to Properly Typed',
    difficulty: 3,
    maxTokens: 2500,
    tags: ['refactoring', 'typescript', 'generics', 'api-client'],
    prompt: [
      'Refactor the following TypeScript API client to eliminate all `any` types and add proper typing. The client wraps a REST API for users and orders.',
      '',
      '```typescript',
      'class ApiClient {',
      '  private baseUrl: string;',
      '  constructor(baseUrl: string) { this.baseUrl = baseUrl; }',
      '',
      '  async get(path: string): Promise<any> {',
      '    const res = await fetch(`${this.baseUrl}${path}`);',
      "    if (!res.ok) throw new Error(`HTTP ${res.status}`);",
      '    return res.json();',
      '  }',
      '',
      '  async post(path: string, body: any): Promise<any> {',
      '    const res = await fetch(`${this.baseUrl}${path}`, {',
      "      method: 'POST',",
      "      headers: { 'Content-Type': 'application/json' },",
      '      body: JSON.stringify(body),',
      '    });',
      "    if (!res.ok) throw new Error(`HTTP ${res.status}`);",
      '    return res.json();',
      '  }',
      '',
      '  async getUser(id: string): Promise<any> {',
      '    return this.get(`/users/${id}`);',
      '  }',
      '',
      '  async createUser(data: any): Promise<any> {',
      "    return this.post('/users', data);",
      '  }',
      '',
      '  async listOrders(userId: string): Promise<any> {',
      '    return this.get(`/users/${userId}/orders`);',
      '  }',
      '}',
      '```',
      '',
      'Requirements:',
      '- Make `get<T>` and `post<T>` generic so callers get typed responses',
      '- Define `User`, `CreateUserInput`, `Order` interfaces with realistic fields',
      '- Type all method signatures — zero `any` remaining',
      '- Define and throw a typed `ApiError` class (not generic `Error`) that includes the HTTP status code',
      '- Preserve the existing method signatures where possible',
    ].join('\n'),
    expectedCapabilities: [
      'generic type parameters on get/post',
      'interface definitions for User, Order',
      'proper return types',
      'typed ApiError class',
      'no any remaining',
    ],
  },

  // ---------------------------------------------------------------------------
  // Architecture (difficulty 3-4)
  // ---------------------------------------------------------------------------
  {
    id: 'arch-001',
    category: 'architecture',
    title: 'Plugin System Design',
    difficulty: 4,
    maxTokens: 4000,
    tags: ['architecture', 'plugins', 'cli', 'typescript'],
    prompt: [
      'Design a TypeScript plugin system for a CLI tool.',
      '',
      'Requirements:',
      '1. Plugins register via a standard `Plugin` interface',
      '2. Plugins can add new CLI commands (name, description, execute function)',
      '3. Plugins have lifecycle hooks: `init`, `beforeCommand`, `afterCommand`, `shutdown`',
      '4. Plugins declare dependencies on other plugins by name',
      '5. The plugin manager detects circular dependencies and throws a descriptive error',
      '6. Plugins are loaded in dependency order (topological sort)',
      '',
      'Deliverables:',
      '- Type definitions for `Plugin`, `Command`, `PluginContext`, and lifecycle hook types',
      '- `PluginManager` class implementation with `register`, `loadAll`, `runCommand`, and `shutdown` methods',
      '- Circular dependency detection with a clear error message naming the cycle',
      '- An example plugin (`LoggingPlugin`) that depends on no other plugins and logs lifecycle events',
      '- Brief inline comments explaining the topological sort approach',
    ].join('\n'),
    expectedCapabilities: [
      'clean interface design',
      'lifecycle hooks',
      'dependency resolution',
      'circular dependency detection',
      'topological sort',
      'example plugin',
    ],
  },

  {
    id: 'arch-002',
    category: 'architecture',
    title: 'Rate Limiter with SQLite',
    difficulty: 3,
    maxTokens: 3000,
    tags: ['architecture', 'sqlite', 'rate-limiting', 'typescript'],
    prompt: [
      'Design and implement a sliding window rate limiter in TypeScript backed by SQLite (using better-sqlite3).',
      '',
      'Requirements:',
      '1. Configurable window size (e.g., 60 seconds) and max requests per window',
      '2. Support multiple keys (e.g., per-user rate limiting by user ID, per-IP)',
      '3. Atomic check-and-increment using SQLite transactions',
      '4. Automatic cleanup of expired entries (call during `tryConsume` if expired count > threshold)',
      '5. Public interface: `tryConsume(key: string): { allowed: boolean; remaining: number; resetAt: Date }`',
      '6. Safe for concurrent access within a single process (SQLite serializes writes)',
      '',
      'Deliverables:',
      '- `RateLimiterConfig` interface',
      '- SQLite schema (CREATE TABLE statement with appropriate indexes)',
      '- `RateLimiter` class with constructor, `tryConsume`, and `close` methods',
      '- Explanation of why this approach is safe for concurrent access',
      '- Note any limitations compared to a Redis-backed implementation',
    ].join('\n'),
    expectedCapabilities: [
      'sliding window algorithm',
      'SQLite schema with indexes',
      'atomic operations via transactions',
      'cleanup strategy',
      'proper TypeScript types',
      'concurrent access handling',
    ],
  },

  // ---------------------------------------------------------------------------
  // Debugging (difficulty 2-4)
  // ---------------------------------------------------------------------------
  {
    id: 'debug-001',
    category: 'debugging',
    title: 'Off-by-One Pagination',
    difficulty: 2,
    maxTokens: 1500,
    tags: ['debugging', 'pagination', 'off-by-one'],
    prompt: [
      'The following pagination function has a bug that causes it to skip the last page when the total number of items is exactly divisible by the page size. Find and fix the bug, and explain what was wrong.',
      '',
      '```typescript',
      'interface PaginationResult {',
      '  items: number[];',
      '  currentPage: number;',
      '  totalPages: number;',
      '  hasNext: boolean;',
      '  hasPrev: boolean;',
      '}',
      '',
      'function paginate(allItems: number[], page: number, pageSize: number): PaginationResult {',
      '  const totalPages = Math.floor(allItems.length / pageSize);',
      '  const start = (page - 1) * pageSize;',
      '  const end = start + pageSize;',
      '  const items = allItems.slice(start, end);',
      '  return {',
      '    items,',
      '    currentPage: page,',
      '    totalPages,',
      '    hasNext: page < totalPages,',
      '    hasPrev: page > 1,',
      '  };',
      '}',
      '```',
      '',
      'Requirements:',
      '- Identify the bug (which line, why it is wrong)',
      '- Provide the corrected function',
      '- Explain what happens when `allItems.length` is exactly divisible by `pageSize`',
      '- Also handle the edge case of an empty `allItems` array correctly',
    ].join('\n'),
    expectedCapabilities: [
      'identify Math.floor should be Math.ceil',
      'explain the edge case',
      'correct fix',
      'handle empty array edge case',
    ],
    hiddenTests: [
      {
        description: 'Last page when evenly divisible',
        input: 'paginate([1,2,3,4,5,6], 2, 3)',
        expectedOutput: '{"items":[4,5,6],"currentPage":2,"totalPages":2,"hasNext":false,"hasPrev":true}',
      },
      {
        description: 'First page of exact-divisible set',
        input: 'paginate([1,2,3,4,5,6], 1, 3)',
        expectedOutput: '{"items":[1,2,3],"currentPage":1,"totalPages":2,"hasNext":true,"hasPrev":false}',
      },
      {
        description: 'Empty array',
        input: 'paginate([], 1, 10)',
        expectedOutput: '{"items":[],"currentPage":1,"totalPages":0,"hasNext":false,"hasPrev":false}',
      },
    ],
  },

  {
    id: 'debug-002',
    category: 'debugging',
    title: 'Race Condition in Counter',
    difficulty: 3,
    maxTokens: 2000,
    tags: ['debugging', 'concurrency', 'race-condition', 'async'],
    prompt: [
      'The following code has a race condition. Multiple async operations read and write a shared counter, leading to lost updates. Identify the race condition, explain why it happens, and fix it.',
      '',
      '```typescript',
      'let requestCount = 0;',
      '',
      'async function handleRequest(db: Database, requestId: string): Promise<void> {',
      '  const current = requestCount;',
      "  await db.query('INSERT INTO requests (id) VALUES (?)', [requestId]);",
      '  requestCount = current + 1;',
      '  if (requestCount % 100 === 0) {',
      "    await db.query('INSERT INTO checkpoints (count) VALUES (?)', [requestCount]);",
      '  }',
      '}',
      '',
      '// Called concurrently for each incoming request',
      'async function processRequests(db: Database, ids: string[]): Promise<number> {',
      '  await Promise.all(ids.map(id => handleRequest(db, id)));',
      '  return requestCount;',
      '}',
      '```',
      '',
      'Requirements:',
      '- Identify the exact lines where the race condition occurs',
      '- Explain why `await` causes the interleaving that leads to lost updates',
      '- Propose a fix using a mutex or serialization queue (implement it, do not just describe it)',
      '- The fix should not change the observable behavior (all inserts still happen, count is accurate)',
      '- Type `Database` minimally as needed',
    ].join('\n'),
    expectedCapabilities: [
      'identify TOCTOU race between read and write',
      'explain that await causes interleaving',
      'propose mutex/queue solution',
      'correct implementation',
    ],
  },

  {
    id: 'debug-003',
    category: 'debugging',
    title: 'Timezone Bug in Date Comparison',
    difficulty: 3,
    maxTokens: 2000,
    tags: ['debugging', 'timezone', 'date', 'intl'],
    prompt: [
      "The following function is supposed to check if an event falls on \"today\" in the user's timezone. It works correctly in some timezones but fails in others. Find and fix the bug.",
      '',
      '```typescript',
      'function isToday(eventDate: string, userTimezone: string): boolean {',
      '  const event = new Date(eventDate);',
      '  const now = new Date();',
      '  return event.getFullYear() === now.getFullYear() &&',
      '         event.getMonth() === now.getMonth() &&',
      '         event.getDate() === now.getDate();',
      '}',
      '```',
      '',
      'Example of the failure: when the server is running in UTC and a user in `Asia/Tokyo` (UTC+9) calls `isToday(\'2024-03-15T23:00:00Z\', \'Asia/Tokyo\')` at server time 2024-03-15T23:30:00Z, the function returns `false` even though in Tokyo it is already 2024-03-16.',
      '',
      'Requirements:',
      '- Identify why the comparison ignores `userTimezone`',
      '- Fix the function to correctly compare dates in the user\'s timezone',
      '- Use `Intl.DateTimeFormat` or manual UTC offset calculation (no external libraries)',
      '- Handle DST transitions correctly',
      '- Explain why the original code fails and why your fix is correct',
    ].join('\n'),
    expectedCapabilities: [
      'identify that comparison uses server local time, ignoring userTimezone',
      'use Intl.DateTimeFormat or manual UTC offset',
      'handle DST transitions',
      'correct implementation',
    ],
  },

  // ---------------------------------------------------------------------------
  // Multi-file (difficulty 4-5)
  // ---------------------------------------------------------------------------
  {
    id: 'multi-001',
    category: 'multi-file',
    title: 'MCP Tool Implementation',
    difficulty: 4,
    maxTokens: 4000,
    tags: ['mcp', 'multi-file', 'zod', 'typescript'],
    prompt: [
      'Implement a complete MCP (Model Context Protocol) tool that provides a `weather_lookup` capability. Generate all necessary files.',
      '',
      '**File: types.ts**',
      '- `WeatherInput` interface: city (string), units? ("celsius" | "fahrenheit", default celsius)',
      '- `WeatherData` interface: city, temperature (number), feelsLike (number), conditions (string), humidity (number), windSpeed (number), units',
      '',
      '**File: schema.ts**',
      '- Zod schema validating `WeatherInput` with descriptive error messages',
      '- Export the inferred TypeScript type from the schema',
      '',
      '**File: handler.ts**',
      '- `weatherLookupHandler(input: WeatherInput): WeatherData` function',
      '- Use realistic mock data (a few cities hardcoded, fallback for unknown cities)',
      '- Convert between celsius/fahrenheit correctly',
      '- Handle unknown city gracefully (return data with a "conditions" note)',
      '',
      '**File: registration.ts**',
      '- Register the tool with an MCP Server instance following `@modelcontextprotocol/sdk` patterns',
      '- Tool name: `weather_lookup`, include description and input schema',
      '- Use `server.tool()` registration pattern',
      '- Handle validation errors and return proper MCP error responses',
      '',
      'All files should use TypeScript with strict typing and .js import extensions.',
    ].join('\n'),
    expectedCapabilities: [
      'correct MCP tool registration',
      'zod input schema',
      'proper error handling',
      'typed responses',
      'multi-file organization',
      'mock data that looks realistic',
    ],
  },

  {
    id: 'multi-002',
    category: 'multi-file',
    title: 'REST Endpoint with Validation',
    difficulty: 4,
    maxTokens: 5000,
    tags: ['rest', 'express', 'zod', 'vitest', 'multi-file'],
    prompt: [
      'Implement a complete Express.js REST endpoint for managing bookmarks. Generate all necessary files.',
      '',
      '**File: types.ts**',
      '```',
      'Bookmark: { id: string; url: string; title: string; tags: string[]; createdAt: Date; updatedAt: Date }',
      'CreateBookmarkInput: { url: string; title: string; tags?: string[] }',
      'UpdateBookmarkInput: { url?: string; title?: string; tags?: string[] }',
      '```',
      '',
      '**File: validation.ts**',
      '- Zod schema for `CreateBookmarkInput`: url must be a valid URL, title 1-200 chars, tags optional array of non-empty strings',
      '- Zod schema for `UpdateBookmarkInput`: same constraints, all fields optional but at least one must be present',
      '- Export both schemas and their inferred types',
      '',
      '**File: handler.ts**',
      '- In-memory store (Map<string, Bookmark>)',
      '- `GET /bookmarks` — list all, support optional `?tag=` query param filter',
      '- `GET /bookmarks/:id` — get by ID, 404 if not found',
      '- `POST /bookmarks` — create, validate with zod, return 201',
      '- `PUT /bookmarks/:id` — update, validate with zod, 404 if not found',
      '- `DELETE /bookmarks/:id` — delete, 404 if not found, return 204',
      '- Proper TypeScript types for Express req/res',
      '',
      '**File: handler.test.ts**',
      '- Vitest tests covering: create happy path, create with invalid URL (expect 400), get by ID, get non-existent (expect 404), update, delete',
      '- Use supertest or test the handler functions directly (your choice, explain why)',
      '',
      'Use TypeScript throughout with strict typing and .js import extensions.',
    ].join('\n'),
    expectedCapabilities: [
      'clean type definitions',
      'zod validation schemas',
      'proper HTTP status codes',
      'CRUD operations',
      'test coverage',
      'error handling',
    ],
  },

  // ---------------------------------------------------------------------------
  // Reasoning (difficulty 5)
  // ---------------------------------------------------------------------------
  {
    id: 'reason-001',
    category: 'reasoning',
    title: 'CRDT Last-Write-Wins Register',
    difficulty: 5,
    maxTokens: 4000,
    tags: ['crdt', 'distributed-systems', 'vector-clocks', 'typescript'],
    prompt: [
      'Implement a Last-Write-Wins (LWW) Register CRDT (Conflict-free Replicated Data Type) in TypeScript with vector clocks.',
      '',
      'Requirements:',
      '',
      '**Types (define these):**',
      '- `ReplicaId`: string type alias',
      '- `VectorClock`: Record<ReplicaId, number>',
      '- `LWWEntry<T>`: { value: T; timestamp: number; clock: VectorClock; replicaId: ReplicaId }',
      '- `LWWRegister<T>`: class',
      '',
      '**LWWRegister<T> class:**',
      '- `constructor(replicaId: ReplicaId)`',
      '- `write(value: T): void` — write with current wall-clock timestamp and incremented local vector clock component',
      '- `read(): T | undefined` — return current value',
      '- `merge(other: LWWRegister<T>): void` — merge another replica\'s state into this one',
      '  - If clocks are causally ordered (one dominates), keep the causally later value',
      '  - If clocks are concurrent, use wall-clock timestamp as tiebreaker',
      '  - If timestamps are also equal, use lexicographic order on replicaId as final tiebreaker (deterministic)',
      '',
      '**Usage examples (provide these as runnable code):**',
      '1. Two replicas write concurrently, merge resolves via timestamp',
      '2. Sequential writes across replicas, merge correctly tracks causality',
      '3. Three-way merge (A merges B, B merges C, A merges again) converges to the same value',
      '',
      '**Design explanation:**',
      '- Why LWW is "conflict-free" (always converges)',
      '- Why vector clocks are needed (not just wall-clock timestamps)',
      '- The tradeoff: LWW can silently discard writes — when is this acceptable?',
    ].join('\n'),
    expectedCapabilities: [
      'correct vector clock implementation',
      'LWW semantics',
      'merge function',
      'concurrent write handling',
      'causality tracking',
      'clear explanation of design',
    ],
  },
];
